### ISSUE TITLE
it would be very usefull if i can set badge also on TAB LAYOUT

### ISSUE THREAD

**Issue by PaolinoAngeletti** [v2rc/Badger#2]

**Comment by dariush-fathie** [comment]
Mr Paolino Angeletti , bottomNavigationView now support badge

**Comment by SoftwareAdvise** [comment]
i dont talk about bottomNavigationMenu, but tabLayout.
![immagine](https://user-images.githubusercontent.com/9363586/65223921-73092300-dac2-11e9-94ad-ca702f45c9e0.png)

**Comment by SoftwareAdvise** [comment]
maybe i can try setting a custom view to tab layout item .. I'll try and update you!

**Comment by SoftwareAdvise** [comment]
it may be very usefull also on general views.

**Comment by tynn** [comment]
Hej @PaolinoAngeletti @SoftwareAdvise, I'm sorry for the late reply. This library only intends to add badges to a `Drawable`, not to a `View`. The `TabLayout` is mostly text therefore this library might not be the right one for your needs. You might be able to use it with the background though.

**Comment by PaolinoAngeletti** [comment]
mmm yes, but we can round the problem setting tab item as a view.
so, if you can implement setting badge on a general view (you've done it for image view, maybe you can do it with View, too) i can implement a way to solve the problem, and if you want i can explain this way to you..

**Comment by tynn** [comment]
Which `Drawable` from a plain `View` would you choose? But if you have a good use-case for yourself, you could just implement the method within your domain. The method for `ImageView` is just three lines of code wrapping around `sett(Drawable,Factory)`:

    public static <T extends BadgeDrawable> T sett(@NonNull ImageView view, @NonNull BadgeDrawable.Factory<? extends T> factory) {
        Badger<T> badger = sett(view.getDrawable(), factory);
        view.setImageDrawable(badger.drawable);
        return badger.badge;
    }
