### ISSUE TITLE
Set the Badge value outside  onOptionsItemSelected

### ISSUE THREAD

**Issue by ghost** [v2rc/Badger#6]
Hello, first of all thanks you for your awesome library. (I'm with Kotlin)
I'm trying to make a little changes, I want to change the badge value in the activity onCreate 

I got this code in onCreateOptionsMenu :

``` 
ovalSquare = CountBadge.Factory(this, BadgeShape.oval(1f, 2f, Gravity.BOTTOM))
Badger.sett(menu.findItem(R.id.profil), ovalSquare).count = badge
```

but to set the final value in the onCreate I got exception: variable  theBadge was not initialised 
onCreate Activity 

```  
@SuppressWarnings("ConstantConditions")
val theBadge: CountBadge = Badger.sett(theItem, ovalSquare)
theBadge.count = badge
```

Please can you help me ?

**Comment by tynn** [comment]
You might need to provide more code and a stacktrace for the exception as well. Could you add this information to your issue?

But from what I see, you might want to not `@SuppressWarnings("ConstantConditions")` as it's a valid warning.

**Comment by ghost** [comment]
I just to need get the variable countBadge Updated because the value is onCreapteOptionsMenu
and I need it updated in Activity onCreate I think I need a observer or interface ...

**Comment by ghost** [comment]
i fixed something and the main problem is that the variable countBadge is null(I created it in onCreate) , because onCreate comes before the onCreateOptionsMenu...

**Comment by ghost** [comment]
in your Example you get the badgeCount updated in the onOptionsitemSelected.. that nice but I want it as a variable to update it in onCreate activity

**Comment by tynn** [comment]
Why do you need to set the value in `onCreate` exactly? Would it be an option to do that work in `onCreateOptionsMenu` or `onStart`?

Due to the order of `onCreate` -> `onCreateOptionsMenu` -> `onOptionsItemSelected` the badge is not setup when `onCreate` is running.

Please post your code to help me help you.

**Comment by ghost** [comment]
You right , and onCreate onOcreateOptions is called once... I'm updating the value after  the activity's inflate and every time I click a Button ..

let me post some code so you can understand me

**Comment by ghost** [comment]
You get the badge value updated when you click onOptionsItemSelected...
how can I get the badge value updated in the lifecycle every time I click a random button in an activity... ?

**Comment by tynn** [comment]
Just add the change to the `View.OnClickListener` you set for the button. By the time the user has access to any button, the menu item should be available already.

**Comment by ghost** [comment]
the Button is in the Toolbar sir, so theItem.setOnMenuClickListener {} ?

**Comment by tynn** [comment]
Just add your code please.

**Comment by ghost** [comment]
Thanks for your help sir, It's working  :) 
Stay safe.
