### ISSUE TITLE
Does it work for BottomNavigationView?

### ISSUE THREAD

**Issue by behnamk** [v2rc/Badger#7]
Does it work for BottomNavigationView?
What brands does it work for?
How much does it support Android?

**Comment by tynn** [comment]
It works with [`BottomNavigationView.getMenu()`](https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView#getmenu).
Brands don't matter.
It's written for Android.

Anyhow it's old and for a `BottomNavigationView` you should use [`getOrCreateBadge()`](https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView#getorcreatebadge) instead.
