### ISSUE TITLE
it doen't work on menu item

### ISSUE THREAD

**Issue by PaolinoAngeletti** [v2rc/Badger#9]
`CountBadge.Factory c = new CountBadge.Factory(context, BadgeShape.circle(.5f, Gravity.END | Gravity.TOP));
                    c.createBadge().setCount(qnt);
                    Badger.sett(elementoTarget, c);`

doesn't work. No badge appears on item;

**Comment by tynn** [comment]
The badge is only shown when the count is greater than 0. Have you called `setCount()` anywhere in you code?

**Comment by SoftwareAdvise** [comment]
this is my istruction:

``

`
Badger.sett(targetElement, createBadgeFactory(context)).setCount(qnt);

@NonNull
    private static CountBadge.Factory createBadgeFactory(@Nullable final Context context)
    {
        return new CountBadge.Factory(new MPBadgeView(context, SCALE_FACTOR, GRAVITY), Color.RED, Color.WHITE);
    }
`

**Comment by tynn** [comment]
Did you verify that `qnt` is greater than 0?
Does it work with a default `BadgeShape` like `circle(.5f, TOP | END)`?
